name: CD al pushear

on:
  push:
    branches:
      - main
      - qa
      - dev

env:
  IMAGE_NAME: polichess-back
  REGISTRY: ghcr.io
  WRITE_PACKAGES: ${{ secrets.WRITE_PACKAGES }}

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2
      
      - name: Instalar Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Iniciar sesión en GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.WRITE_PACKAGES }}
      
      - name: Configurar variable de entorno de nombre del repositorio
        run: echo "REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Hacer el build y subir la imagen Docker
        run: |
          echo "${{ secrets.DEV }}" > dev_secret.txt
          docker build --build-arg DEV_FILE=dev_secret.txt --tag ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} .
          docker push ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
        env:
          DEV: ${{ secrets.DEV }}
